### ISSUE TITLE
Add a configuration option for slippy map tiles

### ISSUE THREAD

**Issue by hrishiballal** [wing-aviation/InterUSS-Platform#24]
**Is your feature request related to a problem? Please describe.**
At the moment the `ConvertCoordinatesToSlippy` method returns tiles from Openstreetmap, we should make this configurable for any slippy map. 
**Describe the solution you'd like**
A configurable option for basemap / slippy maps for e.g from [Openmaptiles](https://openmaptiles.com/) or [Thunderforest](https://www.thunderforest.com/maps/opencyclemap/) and others.

**Describe alternatives you've considered**

**Additional context**
I am happy to submit a PR if we can have a discussion on where is the best place to put this, as a environment variable or others. These maps services are not free and generally have a Key or identifer associated with them.

**Comment by BenjaminPelletier** [comment]
The new ASTM standard abstracts the grid cell format away from clients and uses S2 cells for internal DSS instance synchronization.  Since the TCL4 branch is nearing end of life, I don't think we would plan to implement this feature in that branch.  We can reopen this issue if this feature is relevant to the upcoming updated implementation, but closing for now.
