### ISSUE TITLE
Grid UVR needs to be in sync with NASA's UVR model on v4-draft

### ISSUE THREAD

**Issue by myspri** [wing-aviation/InterUSS-Platform#67]
@BenjaminPelletier, we have updated UVR model
https://github.com/nasa/utm-apis/blob/v4-draft/utm-domains/utm-domain-commons.yaml

This is usually announced in the uss_implementor's channel.
Going forward, we will give you advance notice that will allow our models to be in sync before the announcement goes out.

Can you please update your model based on this?

We have been trying to codegen from your version and have encountered a problem with "allOf" attribute. We are currently blocked. I believe the v4-draft does not include this attribute.

Hopefully, this problem will go away after you sync up with our version.

**To Reproduce**
Unable to codegen from the current Grid UVR model

**Expected behavior**
Should be able to codegen from Grid UVR model

**Additional context**

**Comment by BenjaminPelletier** [comment]
There are 3 things that need to be addressed:
1) Incorporate [required_support](https://github.com/nasa/utm-apis/commit/847c825666236f0802dfbce2f66d7794ea77b8e0#diff-f5f046557feb929288178e7279f8b106)
2) Make type [required](https://github.com/nasa/utm-apis/commit/847c825666236f0802dfbce2f66d7794ea77b8e0#diff-f5f046557feb929288178e7279f8b106)
3) Remove allOf: attributes because `swagger-codegen` can't handle them.  This will hide the documentation for these fields on the SwaggerHub page, but that is necessary to get the codegen to work.
